apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: royal-dolphin-dotnet-basic-prod
  namespace: rhtap
  finalizers: ["resources-finalizer.argocd.argoproj.io"] 
spec:
  project: default
  source:
    path: ./components/royal-dolphin-dotnet-basic/overlays/prod
    repoURL: https://github.com/rhtap-rhdh-qe/royal-dolphin-dotnet-basic-gitops.git
    targetRevision: main
  destination:
    namespace: rhtap-e2e-ci-prod
    server: https://kubernetes.default.svc
  syncPolicy:
    managedNamespaceMetadata:
      labels: 
        argocd.argoproj.io/managed-by: rhtap
    automated: 
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
